CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# Enable status advertisement
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="MyKeyboard"


# Split keyboard only: enable peripheral battery fetching
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"        # Which side is central (LEFT/RIGHT)